/*
 * generated by Xtext 2.39.0
 */
package org.xtext.example.udb.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.udb.udb.UdbPackage;
import org.xtext.example.udb.treetop.TreetopParser;
import org.xtext.example.udb.treetop.ValidationError;

import org.xtext.example.udb.udb.Url;
import org.xtext.example.udb.udb.Email;
import org.xtext.example.udb.udb.StringArray;

import org.xtext.example.udb.udb.CsrModel;
import org.xtext.example.udb.udb.CsrName;
import org.xtext.example.udb.udb.CsrAddress;
import org.xtext.example.udb.udb.CsrVirtualAddress;
import org.xtext.example.udb.udb.CsrIndirectAddress;
import org.xtext.example.udb.udb.CsrIndirectSlot;
import org.xtext.example.udb.udb.CsrLength;
import org.xtext.example.udb.udb.CsrIntType;
import org.xtext.example.udb.udb.CsrFieldDef;
import org.xtext.example.udb.udb.CsrFieldAliasName;
import org.xtext.example.udb.udb.CsrSwRead;
import org.xtext.example.udb.udb.CsrFieldResetValueFunc;
import org.xtext.example.udb.udb.CsrFieldSWWriteFunc;
import org.xtext.example.udb.udb.CsrFieldLegalFunc;
import org.xtext.example.udb.udb.CsrFieldTypeFunc;

import org.xtext.example.udb.udb.InstModel;
import org.xtext.example.udb.udb.InstName;
import org.xtext.example.udb.udb.InstHints;
import org.xtext.example.udb.udb.InstFormat;
import org.xtext.example.udb.udb.InstOldEncoding;
import org.xtext.example.udb.udb.InstEncoding;
import org.xtext.example.udb.udb.InstEncodingMatch;
import org.xtext.example.udb.udb.InstHintElement;
import org.xtext.example.udb.udb.InstOpcodeEntry;
import org.xtext.example.udb.udb.InstOpcodeInherits;
import org.xtext.example.udb.udb.InstRvPairEncoding;
import org.xtext.example.udb.udb.InstEncodingTwoKeyVar;
import org.xtext.example.udb.udb.InstEncodingSevenKeyVar;
import org.xtext.example.udb.udb.InstEncodingVariables;
import org.xtext.example.udb.udb.InstOperation;

import org.xtext.example.udb.udb.InstOpcodeModel;
import org.xtext.example.udb.udb.InstOpcodeData;


import org.xtext.example.udb.udb.ExtModel;
import org.xtext.example.udb.udb.ExtName;
import org.xtext.example.udb.udb.ExtVersionArrayElement;

import org.xtext.example.udb.udb.InterruptCodeModel;
import org.xtext.example.udb.udb.IntrptCodeName;

import org.xtext.example.udb.udb.ExceptionCodeModel;

import org.xtext.example.udb.udb.InstVarTypeModel;
import org.xtext.example.udb.udb.VarTypeEnum;

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class UdbValidator extends AbstractUdbValidator {

	// Regex's found in schema_defs.json
	String rviVersionRegex = "^[0-9]+(\\.[0-9]+(\\.[0-9]+(-pre)?)?)?$";
	String csrFieldRegex = "^[a-z][a-z0-9_.]+\\.[A-Z0-9]+$";
    String csrFieldBitsRegex = "^[a-z][a-z0-9_.]+\\.[A-Z0-9]+\\[[0-9]+(:[0-9]+)?\\]$";
    String csrNameRegex = "^[a-z][a-z0-9_.]+$";
    String csrAffectedByRegex = "^(RV64)|([A-WY]|(Z[a-z]+)|(S[a-z]+))$";
    String extensionNameRegex = "^(([A-WY])|([SXZ][a-z0-9]+))$";
    String instNameRegex= "[a-z0-9.]+";
    String instHintsRegex = "^\\$ref:\\s*inst/.+\\.yaml#.*$";
    String instInheritTypeRegex="^.+\\.yaml#(/.*)?$";
    String instOpcodeInheritTypeRegex="inst_opcode/[^/]+\\.yaml#/data";
    String instChildOfRegex="common/inst_variable_types\\.yaml#/[a-zA-Z0-9_]+";
    String ENC_48 = "^[01-]{43}11111$";
    String ENC_32 = "^[01-]{30}11$";
    String ENC_16 = "^[01-]{14}((00)|(01)|(10))$";
    String legalIDLName="^[a-zA-Z_][a-zA-Z0-9_]*$";
    

    // Extra regex's for validation
    String urlRegex = "^https?:\\/\\/[^\\s/$.?#].[^\\s]*$";
    String refUrlRegex = "^.*/.*\\.yaml#.*$";
    String emailRegex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
    
    
    



    /*
     * CSR Validation -- rules found in csr_schema.json
     */
    
    /*
     * Ensure CSR schema matches csr_schema.json#
     */
    @Check
    public void checkCsrSchema(CsrModel csr) {
		String schema = csr.getSchema().getSchema();
		if (!schema.equals("csr_schema.json#")) {
			error("Schema incompatible with kind", csr.getSchema(),
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
    
    /*
     * Validate CSR name matches required pattern
     */
	@Check
	public void checkCsrName(CsrName name) {
	    String value = name.getName();
	    if (!value.matches(csrNameRegex)) {
	        error("Invalid csr name",
	              UdbPackage.Literals.CSR_NAME__NAME);
	    }
	}
	
	/*
	 * Validate CSR address is between 0 and 12 bits
	 */
	@Check
	public void checkCsrAddressVal(CsrAddress address) {
		// Address must be between 0 and 12 bits
		int val = address.getAddress().getValue();
		if (val < 0 || val > 4096) {
			error("Address must be between 0 and 12 bits.", UdbPackage.Literals.CSR_ADDRESS__ADDRESS);
		}
	}
	
	/*
	 * Validate CSR virtual address is between 0 and 12 bits
	 */
	@Check
	public void checkCsrVirtualAddressVal(CsrVirtualAddress vaddress) {
		// Virtual address must be between 0 and 12 bits
		// TODO: it doesn't say that in the schema?
		int val = vaddress.getVirtualAddress().getValue();

		if (val < 0 || val > 4096) {
			error("Virtual address must be between 0 and 12 bits.",
					UdbPackage.Literals.CSR_VIRTUAL_ADDRESS__VIRTUAL_ADDRESS);
		}
	}
	
	/*
	 * Validate CSR indirect address is between 0 and 64 bits
	 */
	@Check
	public void checkCsrIndirectAddressVal(CsrIndirectAddress iaddress) {
		// Indirect address must be between 0 and 64 bits
		int val = iaddress.getIndirectAddress().getValue();

		if(val < 0 || val > (2^64)) {
			error("Indirect address must be between 0 and 64 bits.",
					UdbPackage.Literals.CSR_INDIRECT_ADDRESS__INDIRECT_ADDRESS);
		}
	}
	
	/*
	 * Validate indirect slot value is between 1 and 6
	 */
	@Check
	public void checkCsrIndirectSlotVal(CsrIndirectSlot indirectSlot) {
		// indirect_slot must be between 1 and 6
		int slot = indirectSlot.getIndirectSlot();

		if (slot < 1 || slot > 6) {
			error("Indirect slot value must be between 1 and 6.",
					UdbPackage.Literals.CSR_INDIRECT_SLOT__INDIRECT_SLOT);
		}
	}
	
	/*
	 * Ensure indirect slot is present when indirect address is specified
	 */
	@Check
	public void checkCsrIndirectSlot(CsrModel csr) {
		CsrIndirectAddress iaddress = csr.getIndirectAddress();

		if (iaddress != null) {
			if (csr.getIndirectSlot() == null) {
				error("Indirect address requires an indirect slot.",
						UdbPackage.Literals.CSR_MODEL__INDIRECT_ADDRESS);
			}
		}

	}
	
	/*
	 * Validate privilege mode is one of: M, S, U, VS, D
	 */
	@Check
	public void checkCsrPrivMode(CsrModel csr) {
		String mode = csr.getPrivmode() != null ? csr.getPrivmode().getPrivMode() : null;
		java.util.Set<String> ALLOWED_TYPES = java.util.Set.of("M","S","U","VS","D");

		if (mode != null && !ALLOWED_TYPES.contains(mode)) {
		    error(
		        "Invalid privilege mode: " + mode,
		        UdbPackage.Literals.CSR_MODEL__PRIVMODE
		    );
		}
	}
	
	/*
	 * Ensure virtual address is present when privilege mode is VS
	 */
	@Check
	public void checkCsrVirtualAddress(CsrModel csr) {
		String mode = csr.getPrivmode() != null ? csr.getPrivmode().getPrivMode() : null;

		if (mode.equals("VS")) {
			if (csr.getVirtualAddress() == null) {
				error("VS mode requires a virtual address.",
						UdbPackage.Literals.CSR_MODEL__PRIVMODE);
			}
		}

	}
	
	/*
	 * Validate length is either 32 or 64 when specified as integer
	 */
	@Check
	public void checkLengthValue(CsrLength length) {
		CsrIntType lengthInt = length.getLength().getIntType();

		// Containment reference is always instantiated
		if (length.getLength() == null) {
			error("length should not be null",
					UdbPackage.Literals.CSR_LENGTH__LENGTH);
		}

		// If length is an integer, value is either 32 or 64
		if (lengthInt != null) {
			int lengthVal = lengthInt.getIntVal();
			if (lengthVal != 32 && lengthVal != 64) {
				error("length if specified as integer, should be 32 or 64",
						UdbPackage.Literals.CSR_LENGTH__LENGTH);
			}
		}
	}

	/*
	 * Validate CSR field name starts with alphabetic character
	 */
	@Check
	public void checkCsrFieldName(CsrFieldDef field) {
		String value = field.getName();
		if (!value.matches("^[a-zA-Z].*$")) {
			error("Invalid field name",
					UdbPackage.Literals.CSR_FIELD_DEF__NAME);
		}
	}
	
	/*
	 * Validate CSR field alias matches CSR_FIELD or CSR_FIELD_BITS format
	 */
	@Check
	public void checkCsrFieldAlias(CsrFieldAliasName alias) {
		String value = alias.getName();

	    if (!value.matches(csrFieldRegex) &&
	        !value.matches(csrFieldBitsRegex)) {

	        error(
	            "Alias must match CSR_FIELD or CSR_FIELD_BITS format",
	            UdbPackage.Literals.CSR_FIELD_ALIAS_NAME__NAME
	        );
	    }
	}




	/*
	 * Instruction Validation -- rules found in inst_schema.json
	 */
	
	/*
	 * Ensure instruction schema matches inst_schema.json#
	 */
	@Check
	public void checkInstSchema(InstModel inst) {
		/* Ensure base value is either 32 or 64 */
		String schema = inst.getSchema().getSchema();
		if (!schema.equals("inst_schema.json#")) {
			error("Schema incompatible with kind", inst.getSchema(), UdbPackage.Literals.SCHEMA__SCHEMA);
		}
	}
	
	/*
	 * Validate instruction name matches required pattern
	 */
	@Check
	public void checkInstName(InstName name) {
	    String value = name.getName();
	    if (!value.matches(instNameRegex)) {
	        error("Invalid inst name", name, UdbPackage.Literals.INST_NAME__NAME);
	    }
	}



	/*
	 *  Check access detail field is present when at least one mode
	 *  within access field is sometimes
	 */
	@Check
	public void checkInstAccessDetail(InstModel inst) {
		String accessdetail = inst.getAccessDetail() != null ? inst.getAccessDetail().getAccessDetail(): null;

		String m = inst.getAccess().getM() != null ? inst.getAccess().getM().getAccessLevel(): null;
		String s = inst.getAccess().getS() != null ? inst.getAccess().getS().getAccessLevel(): null;
		String u = inst.getAccess().getU() != null ? inst.getAccess().getU().getAccessLevel(): null;
		String vs = inst.getAccess().getVs() != null ? inst.getAccess().getVs().getAccessLevel(): null;
		String vu = inst.getAccess().getVu() != null ? inst.getAccess().getVu().getAccessLevel(): null;


		if (accessdetail == null || accessdetail.trim().isEmpty()) {
			if ("sometimes".equals(m)) {
				error("Must provide access_detail field when at least one access type is sometimes",inst.getAccess(), UdbPackage.Literals.INST_ACCESS__M);
			}
			if ("sometimes".equals(s)) {
				error("Must provide access_detail field when at least one access type is sometimes",inst.getAccess(), UdbPackage.Literals.INST_ACCESS__S);
			}
			if ("sometimes".equals(u)) {
				error("Must provide access_detail field when at least one access type is sometimes",inst.getAccess(), UdbPackage.Literals.INST_ACCESS__U);
			}
			if ("sometimes".equals(vs)) {
				error("Must provide access_detail field when at least one access type is sometimes",inst.getAccess(), UdbPackage.Literals.INST_ACCESS__VS);
			}
			if ("sometimes".equals(vu)) {
				error("Must provide access_detail field when at least one access type is sometimes",inst.getAccess(), UdbPackage.Literals.INST_ACCESS__VU);
			}

		}
	}
	
	/*
	 * Validate instruction hints follow format $ref: inst/<path>.yaml#
	 */
	@Check
	public void checkInstHints(InstHints hints) {
		EList<InstHintElement> hintValue = hints != null ? hints.getHints(): null;

		for (InstHintElement hint : hintValue) {
			String hintString = hint.getHint();

			if (!(hintString.matches(instHintsRegex))) {
				error("hints must be of format $ref: inst/<path>.yaml# or $ref: inst/<path>.yaml#/...", hints, UdbPackage.Literals.INST_HINTS__HINTS);
			}
		}
	}
	
	/*
	 * Validate instruction inherits addresses match expected format
	 */
	@Check
	public void checkInstInherits(InstFormat format) {
	  if (format == null) return;

	  // 1. top-level inherits list
	  if (format.getInherits() != null && format.getInherits().getReference() != null) {
	    for (String address : format.getInherits().getReference()) {
	      if (address == null) continue; // or error if you want to require it
	      if (!address.matches(instInheritTypeRegex)) {
	        error(
	          "$inherits field must follow expected format: <path>.yaml# or <path>.yaml#/<fragment>.",
	          format,
	          UdbPackage.Literals.INST_FORMAT__INHERITS
	        );
	      }
	    }
	  }

	  // 2. opcode inherits
	  if (format.getOpcodes() == null || format.getOpcodes().getOpcode() == null) return;

	  for (InstOpcodeEntry entry : format.getOpcodes().getOpcode()) {
	    if (entry instanceof InstOpcodeInherits opcodeInherits) {
	      String address = opcodeInherits.getInheritsAddress();
	      if (address == null) continue;
	      if (!address.matches(instOpcodeInheritTypeRegex)) {
	        error(
	          "$inherits field within opcodes must follow string address format inst_opcode/<file>.yaml#/data",
	          opcodeInherits,
	          UdbPackage.Literals.INST_OPCODE_INHERITS__INHERITS_ADDRESS
	        );
	      }
	    }
	  }
	}

	/*
	 * Validate instruction encoding match patterns for 16, 32, and 48-bit encodings
	 */
	@Check
	public void checkInstEncoding(InstEncoding encoding) {

		if (encoding instanceof InstOldEncoding) {
			InstOldEncoding oldEncoding = (InstOldEncoding) encoding;

			InstEncodingMatch match = oldEncoding.getMatch();
			String pattern = match.getPattern();
			//error(match + " this is match", UdbPackage.Literals.INST_MODEL__ENCODING);

			// if match doesn't match any of these
			if (!(pattern.matches(ENC_48)) && !(pattern.matches(ENC_16)) && !(pattern.matches(ENC_32))) {
				error("Expected match to follow one of these patterns: 48-bit ([01-]{43}11111), 32-bit ([01-]{30}11), or  16-bit ([01-]{14}(00|01|10)).", match, UdbPackage.Literals.INST_ENCODING_MATCH__PATTERN);
			}
		}

		else if (encoding instanceof InstRvPairEncoding) {
			InstRvPairEncoding rvEncoding = (InstRvPairEncoding) encoding;

			InstEncodingMatch Rv32Match = rvEncoding.getRv32().getMatch();
			InstEncodingMatch Rv64Match = rvEncoding.getRv64().getMatch();
			String Rv32Pattern = Rv32Match.getPattern();
			String Rv64Pattern = Rv64Match.getPattern();
			//error(Rv32match + " this is rv32 match", UdbPackage.Literals.INST_MODEL__ENCODING);
			//error(Rv64match + " this is rv64 match", UdbPackage.Literals.INST_MODEL__ENCODING);

			// if match doesn't match any of these
			if (!(Rv32Pattern.matches(ENC_48)) && !(Rv32Pattern.matches(ENC_16)) && !(Rv32Pattern.matches(ENC_32))) {
				error("Expected match to follow one of these patterns: 48-bit ([01-]{43}11111), 32-bit ([01-]{30}11), or  16-bit ([01-]{14}(00|01|10)).", Rv32Match, UdbPackage.Literals.INST_ENCODING_MATCH__PATTERN);
			}

			if (!(Rv64Pattern.matches(ENC_48)) && !(Rv64Pattern.matches(ENC_16)) && !(Rv64Pattern.matches(ENC_32))) {
				error("Expected match to follow one of these patterns: 48-bit ([01-]{43}11111), 32-bit ([01-]{30}11), or  16-bit ([01-]{14}(00|01|10)).", Rv64Match, UdbPackage.Literals.INST_ENCODING_MATCH__PATTERN);
			}
		}

	}

	/*
	 * Validate $inherits and $child_of fields in encoding variables
	 */
	@Check
	public void checkInstInheritsAndChildOf(InstEncoding encoding) {

		if (!(encoding instanceof InstOldEncoding)) {
			return;
		}

		InstOldEncoding old = (InstOldEncoding) encoding;
		InstEncodingVariables varsList = old.getVariables();

		if (varsList == null) {
			return;
		}

		for (EObject var: varsList.getVars()) {
			if (var instanceof InstEncodingTwoKeyVar) {
				InstEncodingTwoKeyVar twoKey = (InstEncodingTwoKeyVar) var;
				String inherits = twoKey.getInherits();

				if (inherits != null && !(inherits.matches(instChildOfRegex))) {
					error("Expected $inherits to follow common/inst_variable_types\\.yaml#/SOMETHING format", twoKey, UdbPackage.Literals.INST_ENCODING_TWO_KEY_VAR__INHERITS);
				}
			} else if (var instanceof InstEncodingSevenKeyVar) {
				InstEncodingSevenKeyVar sevenKey = (InstEncodingSevenKeyVar) var;
				String childOf = sevenKey.getChildOf();

				if (childOf != null && !(childOf.matches(instChildOfRegex))) {
					error("Expected $child_of to follow common/inst_variable_types\\.yaml#/SOMETHING format", sevenKey, UdbPackage.Literals.INST_ENCODING_SEVEN_KEY_VAR__CHILD_OF);
				}
			}
		}
	}


	/*
	 * Extension Validation -- rules found in ext_schema.json
	 */
	
	/*
	 * Ensure extension schema matches ext_schema.json#
	 */
    @Check
    public void checkExtSchema(ExtModel ext) {
		String schema = ext.getSchema().getSchema();
		if (!schema.equals("ext_schema.json#")) {
			error("Schema incompatible with kind", ext.getSchema(),
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
    
    /*
     * Validate extension name matches required pattern
     */
	@Check
	public void checkExtName(ExtName name) {
	    String value = name.getName();
	    if (!value.matches(extensionNameRegex)) {
	        error("Invalid extension name",
	              UdbPackage.Literals.EXT_NAME__NAME);
	    }
	}
	
	
	/*
	 * Validate extension version format and ratification date requirements
	 */
	@Check
	public void checkExtVersionArrayElement(ExtVersionArrayElement elem) {
		// Validate elements in the versions array

		// check that the string representation of the version is valid
    	String versionString = elem.getVersion();
    	if (!versionString.matches(rviVersionRegex)) {
			error("Invalid version", UdbPackage.Literals.EXT_VERSION_ARRAY_ELEMENT__VERSION);
		}

    	// if state is ratified, a ratification date must be given
    	String versionState = elem.getVersionState().getState();
		if (versionState.equals("ratified")) {
			if (elem.getRatificationDate() == null) {
				error("Ratified states require a ratification date.",
						UdbPackage.Literals.EXT_VERSION_ARRAY_ELEMENT__VERSION_STATE);
			}
		}
	}

	/*
	 * Interrupt Code Validation -- rules found in interrupt_code_schema.json
	 */
	
	/*
	 * Ensure interrupt code schema matches interrupt_code_schema.json#
	 */
	@Check
    public void checkInterruptSchema(InterruptCodeModel intrptModel) {
		String schema = intrptModel.getSchema().getSchema();
		if (!schema.equals("interrupt_code_schema.json#")) {
			error("Schema incompatible with kind", intrptModel.getSchema(),
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
	
	/*
	 * Validate interrupt code name is a legal IDL variable name
	 */
	@Check
	public void checkInterruptName(IntrptCodeName intrptName) {
		// Check that interrupt code name is legal IDL variable name
		String value = intrptName.getName();
	    if (!value.matches(legalIDLName)) {
	        error("Invalid interrupt code name, must be legal IDL variable name",
	              UdbPackage.Literals.INTRPT_CODE_NAME__NAME);
	    }

	}

	/*
     * Exception Code Validation -- rules found in exception_code_schema.json
     */
	
	/*
	 * Ensure exception code schema matches exception_code_schema.json#
	 */
	@Check
    public void checkExceptionCodeSchema(ExceptionCodeModel model) {
		String schema = model.getSchema().getSchema();
		if (!schema.equals("exception_code_schema.json#")) {
			error("Schema incompatible with kind", model.getSchema(),
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
	
	/*
	 * Inst Opcode Validation -- rules found in inst_opcode_schema.json
	 */
	
	/*
	 * Ensure instruction opcode schema matches inst_opcode_schema.json#
	 */
	@Check
    public void checkInstOpcodeSchema(InstOpcodeModel instop) {
		String schema = instop.getSchema().getSchema();
		if (!schema.equals("inst_opcode_schema.json#")) {
			error("Schema incompatible with kind", instop.getSchema(), 
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
	
	
	/*
	 * Validate parent_of field follows ref url format
	 */
	@Check
	public void checkInstOpcodeParentOf(InstOpcodeData instopData) {
	    StringArray parentOfArray = instopData.getParentOf();
	    String parentOfString = instopData.getParentOfString();
	    
	    // Check single string case
	    if (parentOfString != null && !parentOfString.matches(refUrlRegex)) {
	        error("Invalid ref url. Expected a .yaml file path with an anchor, like schemas/my-file.yaml#SectionName", 
	              instopData, UdbPackage.Literals.INST_OPCODE_DATA__PARENT_OF_STRING);
	    }
	    
	    // Check array case
	    if (parentOfArray != null) {
	        for (String item : parentOfArray.getItem()) {
	            if (!item.matches(refUrlRegex)) {
	                error("Invalid ref url. Expected a .yaml file path with an anchor, like schemas/my-file.yaml#SectionName",
	                      instopData, UdbPackage.Literals.INST_OPCODE_DATA__PARENT_OF);
	            }
	        }
	    }
	}
	
	/*
	 * InstVarType Validation -- rules found in inst_var_type_schema.json
	 */
	
	/*
	 * Ensure instruction variable type schema matches inst_var_type_schema.json#
	 */
	@Check
    public void checkInstVarTypeSchema(InstVarTypeModel model) {
		String schema = model.getSchema().getSchema();
		if (!schema.equals("inst_var_type_schema.json#")) {
			error("Schema incompatible with kind", model.getSchema(), 
					UdbPackage.Literals.SCHEMA__SCHEMA);
		}
    }
	
	/*
	 * Validate register_file and access fields for register_reference type
	 */
	@Check
	public void checkRegisterReferenceFields(InstVarTypeModel model) {
		if (model.getInstVarTypeType() == null) return;

	    boolean isRegisterReference = 
	        model.getInstVarTypeType().getType() == VarTypeEnum.REGISTER_REFERENCE;

	    if (isRegisterReference) {
	        // Fields REQUIRED for register_reference
	        if (model.getRegisterFile() == null)
	            error("register_file is required for register_reference type",
	                  UdbPackage.Literals.INST_VAR_TYPE_MODEL__REGISTER_FILE);
	        if (model.getAccess() == null)
	            error("access is required for register_reference type",
	                  UdbPackage.Literals.INST_VAR_TYPE_MODEL__ACCESS);
	    } else {
	        // Fields NOT ALLOWED when type is not register_reference
	        if (model.getRegisterFile() != null)
	            error("register_file is only valid when type is 'register_reference'",
	                  UdbPackage.Literals.INST_VAR_TYPE_MODEL__REGISTER_FILE);
	        if (model.getAccess() != null)
	            error("access is only valid when type is 'register_reference'",
	                  UdbPackage.Literals.INST_VAR_TYPE_MODEL__ACCESS);
	    }
	}
	
	/*
	 * Validate URL follows proper URI format
	 */
	@Check
	public void checkUrlFormat(Url url) {
		// Check that URLs follow the URI format
		String urlString = url.getUrl();
		if (!urlString.matches(urlRegex)) {
			error("URL not in URI format", UdbPackage.Literals.URL__URL);
		}
	}
	
	/*
	 * Validate email follows proper email format
	 */
	public void checkEmailFormat(Email email) {
		// Check that emails follow email format
		String emailString = email.getEmail();
		if (!emailString.matches(emailRegex)) {
			error("Email not in formatted correctly", UdbPackage.Literals.EMAIL__EMAIL);
		}
	}

	/*
	 * Pass off IDL to the treetop parser
	 */
	private final TreetopParser treetopParser = new TreetopParser();

	/**
     * Helper function for passing IDL snippets into treetop
     *
     * @param content   IDL source fragment
     * @param root		Rule name to use as the root (e.g. "function_call"),
     *                  or {@code null} for the grammar's default root.
     */
	public String checkIdl(String content, String root) {
	    // Strip surrounding quotes that Xtext adds to STRING terminals
	    if (content != null && content.startsWith("\"") && content.endsWith("\"")) {
	    	content = content.strip();
	    	content = content.substring(1, content.length() - 1);
	    }

	    ValidationError error = treetopParser.parse(content, root);
	    if (error != null) {
	        return error.reason;
	    }

	    return null;
	}


	// Csr IDL checks
	@Check
	public void checkCsrSwRead(CsrSwRead swRead) {
		String idl = swRead.getSwRead().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.CSR_SW_READ__SW_READ);
		}
	}

	@Check
	public void checkCsrFieldResetValueFunc(CsrFieldResetValueFunc resetVal) {
		String idl = resetVal.getResetValueFunc().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.CSR_FIELD_RESET_VALUE_FUNC__RESET_VALUE_FUNC);
		}
	}

	@Check
	public void checkCsrFieldSWWriteFunc(CsrFieldSWWriteFunc swWrite) {
		String idl = swWrite.getSwWriteFunc().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.CSR_FIELD_SW_WRITE_FUNC__SW_WRITE_FUNC);
		}
	}

	@Check
	public void checkCsrFieldLegalFunc(CsrFieldLegalFunc legal) {
		String idl = legal.getLegalFunc().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.CSR_FIELD_LEGAL_FUNC__LEGAL_FUNC);
		}
	}

	@Check
	public void checkCsrFieldTypeFunc(CsrFieldTypeFunc type) {
		String idl = type.getIdl().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.CSR_FIELD_TYPE_FUNC__IDL);
		}
	}


	// Instruction IDL checks
	@Check
	public void checkInstOperation(InstOperation op) {
		String idl = op.getOperation().getIdl();
		String idlError = checkIdl(idl, "function_body");

		if (idlError != null) {
			error(idlError, UdbPackage.Literals.INST_OPERATION__OPERATION);
		}
	}

}
