// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: CC-BY-4.0

= FAQ
:toc: left
:toclevels: 3
:sectnums:

== Development

=== Run regression tests

To run all locally (takes a long time):

[source,bash]
--
./bin/regress
--

To list regression tests:

[source,bash]
--
./bin/regress --list
--

To run a specific regression test:

[source,bash]
--
# run the 'regress-sorbet' test
./bin/regress --name regress-sorbet
--

To run all regression tests matching a tag:

[source,bash]
--
# run all regressions tagged as 'smoke'
./bin/regress --tag smoke
--

=== Add a new regression

Basic Regressions::
--
Basic (most) regressions that can be run via the command-line within the UDB container are
stored in `tools/test/regress-tests.yaml`.

To add a basic regression, you must:

1. Add the regression in `tools/test/regress-tests.yaml`
    * The main steps of the test should go under the `test` key.
    * If there are any steps needed to set up the test in GitHub CI, add those under the `gh_pre` key.
    * If there are any steps needed after the test in GitHub CI, add those under the `gh_post` key.
2. run `./bin/chore gen regress`
--

See xref:regress-test-infrastructure.adoc[Regression test infrastructure] for more details.

Complex Regressions::
--
Complex regressions are not runnable on the command line. They only run in CI via GitHub Actions.

To add a complex regression, you must:

1. add the steps as a job in `tools/test/regress-gh-template.yaml`
2. run `./bin/chore gen regress`
--

See xref:regress-test-infrastructure.adoc[Regression test infrastructure] for more details.


=== Update Ruby gems

To update Ruby gems to the latest available versions, run:

[source,bash]
----
./bin/chore update gems
----

Then `git add` all updated/new files and make a PR.

=== Add a new Ruby gem

Add the gem in the appropriate Gemfile (top, or one of the sub-project gems under tools/ruby-gems).

Install it on the host:

[source,bash]
----
bundle install
----

Then follow the proceedure in <<Update Ruby gems>>.
