/*
 * generated by Xtext 2.39.0
 */
package org.xtext.example.udb.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.udb.udb.Model

@ExtendWith(InjectionExtension)
@InjectWith(UdbInjectorProvider)
class UdbParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void parsesValidCSR() {
		val result = parseHelper.parse('''
			kind: csr;
			name: vcsr;
			long_name: "Vector Control and Status Register";
			description: "Contains aliases to vxrm and vxsat CSRs";
			definedBy: "V";
			address: 0x00F;
			writable: true;
			priv_mode: U;
			length: MXLEN;
			fields {
			  VXRM {
			    location: 2-1;
			    reset_value: UNDEFINED_LEGAL;
				sw_write(csr_value): "|
			      CSR[vxrm].VALUE = csr_value.VXRM;
			      return csr_value.VXRM;";
			    description: "See vxrm.";
			    type: RW-RH;
			    alias: vxrm.VALUE[1:0];
			  }
			  VXSAT {
			    location: 0;
			    reset_value: UNDEFINED_LEGAL;
				sw_write(csr_value): "|
			      CSR[vxsat].VALUE = csr_value.VXSAT;
			      return csr_value.VXSAT;";
			    description: "See vxsat.";
			    type: RW-RH;
			    alias: vxsat.VALUE[0];
			    
			    
			  }
			}
			
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		
		// check basic inputs
		var k = result.getKind().getKind().getType();
		Assertions.assertEquals("csr", k as String); 
		var n = result.getCsrName().getName().getType();
		Assertions.assertEquals("vcsr", n as String);
		var ln = result.getLongName().getLongName();
		Assertions.assertEquals("Vector Control and Status Register", ln);
		var add = result.getAddress().getAddress().getValue();
		Assertions.assertEquals(0x00F, add);
		var writ = result.getWritable().isWritable();
		Assertions.assertEquals(true, writ);
		var priv = result.getPrivmode().getPrivMode().getType();
		Assertions.assertEquals("U", priv);
		var len = result.getLength().getLength().getType();
		Assertions.assertEquals("MXLEN", len as String);
		var desc = result.getDescription().getDescription();
		Assertions.assertEquals("Contains aliases to vxrm and vxsat CSRs", desc);
		var def = result.getDefinedBy().getExtensionName();
		Assertions.assertEquals("V", def);
		
		// test fields
		var vxrm = result.getFields().getFields().get(0);
		var vxsat = result.getFields().getFields().get(1);
		Assertions.assertEquals("VXRM", vxrm.getName());
		Assertions.assertEquals("VXSAT", vxsat.getName());
		
		// location testing has strange to parse EObject
//		var rmrange = vxrm.getLocation().getLocation().getLocation().getRange();
//		var satloc = vxsat.getLocation().getLocation().getLocation().getValue();
//		Assertions.assertEquals(2, rmrange.getStart());
//		Assertions.assertEquals(1, rmrange.getEnd());
//		Assertions.assertEquals(0, satloc);
		
		// reset value has same issue
//		var rmreset = vxrm.getResetValue().getResetValue().getResetValue().getUndefinedLegal();
//		var satreset = vxsat.getResetValue().getResetValue().getUndefinedLegal();
//		Assertions.assertEquals("UNDEFINED_LEGAL", rmreset as String);
//		var rmsw = vxrm.getSwWriteFunc().getSwWriteFunc().getIdl();
//		var satsw = vxsat.getSwWriteFunc().getSwWriteFunc().getIdl();
		
		// testing multi-line IDL has whitespace issues
//		Assertions.assertEquals("|
//			CSR[vxrm].VALUE = csr_value.VXRM;
//			return csr_value.VXRM;", rmsw);
//		Assertions.assertEquals("|
//			   CSR[vxsat].VALUE = csr_value.VXSAT;
//			   return csr_value.VXSAT;", satsw);

		// testing description of fields
		var rmdesc = vxrm.getDescription().getDescription();
		var satdesc = vxsat.getDescription().getDescription();
		Assertions.assertEquals("See vxrm.", rmdesc);
		Assertions.assertEquals("See vxsat.", satdesc);
		
		// testing field type, eobject issue as well
//		var rmtype = vxrm.getType().getType().getType();
//		var sattype = vxsat.getType().getType().getType();
//		Assertions.assertEquals("RW-RH", rmtype);
//		Assertions.assertEquals("RW-RH", sattype);

		// testing alias
		var vxalias = vxrm.getAlias().getAlias().getAlias().get(0);
		var satalias = vxsat.getAlias().getAlias().getAlias().get(0);
		Assertions.assertEquals("vxrm.VALUE[1:0]", vxalias);
		Assertions.assertEquals("vxsat.VALUE[0]", satalias);
		

		
	}
	

	@Test
	def void rejectsBadHex() throws Exception {
	    
	}
	
	
}