/*
 * generated by Xtext 2.39.0
 */
package org.xtext.clinic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RiscvStandaloneSetup extends RiscvStandaloneSetupGenerated {

	public static void doSetup() {
		new RiscvStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
